// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrktpmcmlvrrqploffnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ya3RwbWNtbHZycnFwbG9mZm5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzQ3NjcsImV4cCI6MjA3MzYxMDc2N30.rH254oAXruhCCbqECve7PMCoi6zD45YwZlct5rWLm4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});